/* tslint:disable */
/* eslint-disable */
/**
 * drant-community
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateNews,
    CreateNewsFromJSON,
    CreateNewsToJSON,
} from '../models';

export interface NewsControllerPostNewsRequest {
    createNews: CreateNews;
}

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI {

    /**
     */
    async newsControllerPostNewsRaw(requestParameters: NewsControllerPostNewsRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.createNews === null || requestParameters.createNews === undefined) {
            throw new runtime.RequiredError('createNews','Required parameter requestParameters.createNews was null or undefined when calling newsControllerPostNews.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/news/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateNewsToJSON(requestParameters.createNews),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async newsControllerPostNews(requestParameters: NewsControllerPostNewsRequest): Promise<void> {
        await this.newsControllerPostNewsRaw(requestParameters);
    }

}
