/* tslint:disable */
/* eslint-disable */
/**
 * drant-community
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetDTO
 */
export interface AssetDTO {
    /**
     * 
     * @type {string}
     * @memberof AssetDTO
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof AssetDTO
     */
    thumbnail: string;
    /**
     * 
     * @type {string}
     * @memberof AssetDTO
     */
    mime: string;
}

export function AssetDTOFromJSON(json: any): AssetDTO {
    return AssetDTOFromJSONTyped(json, false);
}

export function AssetDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'thumbnail': json['thumbnail'],
        'mime': json['mime'],
    };
}

export function AssetDTOToJSON(value?: AssetDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'thumbnail': value.thumbnail,
        'mime': value.mime,
    };
}


