/* tslint:disable */
/* eslint-disable */
/**
 * drant-community
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AssetDTO,
    AssetDTOFromJSON,
    AssetDTOFromJSONTyped,
    AssetDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface RantDTO
 */
export interface RantDTO {
    /**
     * 
     * @type {string}
     * @memberof RantDTO
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof RantDTO
     */
    content: string;
    /**
     * 
     * @type {AssetDTO}
     * @memberof RantDTO
     */
    asset: AssetDTO;
    /**
     * 
     * @type {Array<string>}
     * @memberof RantDTO
     */
    votes: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RantDTO
     */
    comments: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof RantDTO
     */
    owner: object;
    /**
     * 
     * @type {string}
     * @memberof RantDTO
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof RantDTO
     */
    createdAt: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RantDTO
     */
    tags: Array<string>;
}

export function RantDTOFromJSON(json: any): RantDTO {
    return RantDTOFromJSONTyped(json, false);
}

export function RantDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RantDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'content': json['content'],
        'asset': AssetDTOFromJSON(json['asset']),
        'votes': json['votes'],
        'comments': json['comments'],
        'owner': json['owner'],
        'updatedAt': json['updatedAt'],
        'createdAt': json['createdAt'],
        'tags': json['tags'],
    };
}

export function RantDTOToJSON(value?: RantDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'content': value.content,
        'asset': AssetDTOToJSON(value.asset),
        'votes': value.votes,
        'comments': value.comments,
        'owner': value.owner,
        'updatedAt': value.updatedAt,
        'createdAt': value.createdAt,
        'tags': value.tags,
    };
}


