/* tslint:disable */
/* eslint-disable */
/**
 * drant-community
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMessageDTO
 */
export interface CreateMessageDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateMessageDTO
     */
    content: string;
    /**
     * If sent as `multipart/form-data`, provide a binary file,
     * however, you cannot sent binary files using `application/json`.
     * 
     * In that case, you can encode the file as base64, in the following format:
     * `data:[<mediatype>][;base64],<data>`
     * 
     * Please be aware of the limitations of using a base64 file upload.
     * The file limit is calculated BEFORE the base64 file is unpacked.
     * @type {Blob}
     * @memberof CreateMessageDTO
     */
    asset?: Blob;
}

export function CreateMessageDTOFromJSON(json: any): CreateMessageDTO {
    return CreateMessageDTOFromJSONTyped(json, false);
}

export function CreateMessageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessageDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': json['content'],
        'asset': !exists(json, 'asset') ? undefined : json['asset'],
    };
}

export function CreateMessageDTOToJSON(value?: CreateMessageDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
        'asset': value.asset,
    };
}


