/* tslint:disable */
/* eslint-disable */
/**
 * drant-community
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NewsDTO,
    NewsDTOFromJSON,
    NewsDTOFromJSONTyped,
    NewsDTOToJSON,
    RantDTO,
    RantDTOFromJSON,
    RantDTOFromJSONTyped,
    RantDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface FeedDTO
 */
export interface FeedDTO {
    /**
     * 
     * @type {Array<RantDTO>}
     * @memberof FeedDTO
     */
    rants: Array<RantDTO>;
    /**
     * 
     * @type {number}
     * @memberof FeedDTO
     */
    wrw: number;
    /**
     * 
     * @type {NewsDTO}
     * @memberof FeedDTO
     */
    news: NewsDTO;
}

export function FeedDTOFromJSON(json: any): FeedDTO {
    return FeedDTOFromJSONTyped(json, false);
}

export function FeedDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rants': ((json['rants'] as Array<any>).map(RantDTOFromJSON)),
        'wrw': json['wrw'],
        'news': NewsDTOFromJSON(json['news']),
    };
}

export function FeedDTOToJSON(value?: FeedDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rants': ((value.rants as Array<any>).map(RantDTOToJSON)),
        'wrw': value.wrw,
        'news': NewsDTOToJSON(value.news),
    };
}


