/* tslint:disable */
/* eslint-disable */
/**
 * drant-community
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MakeVoteDTO
 */
export interface MakeVoteDTO {
    /**
     * 
     * @type {number}
     * @memberof MakeVoteDTO
     */
    state: number;
}

export function MakeVoteDTOFromJSON(json: any): MakeVoteDTO {
    return MakeVoteDTOFromJSONTyped(json, false);
}

export function MakeVoteDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MakeVoteDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'state': json['state'],
    };
}

export function MakeVoteDTOToJSON(value?: MakeVoteDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'state': value.state,
    };
}


