/* tslint:disable */
/* eslint-disable */
/**
 * drant-community
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AssetDTO,
    AssetDTOFromJSON,
    AssetDTOFromJSONTyped,
    AssetDTOToJSON,
    CommentDTO,
    CommentDTOFromJSON,
    CommentDTOFromJSONTyped,
    CommentDTOToJSON,
    VoteDTO,
    VoteDTOFromJSON,
    VoteDTOFromJSONTyped,
    VoteDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface RantDTO
 */
export interface RantDTO {
    /**
     * 
     * @type {string}
     * @memberof RantDTO
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof RantDTO
     */
    content: string;
    /**
     * 
     * @type {AssetDTO}
     * @memberof RantDTO
     */
    asset: AssetDTO;
    /**
     * 
     * @type {Array<VoteDTO>}
     * @memberof RantDTO
     */
    votes?: Array<VoteDTO>;
    /**
     * 
     * @type {number}
     * @memberof RantDTO
     */
    userVoteState?: number;
    /**
     * 
     * @type {number}
     * @memberof RantDTO
     */
    score: number;
    /**
     * 
     * @type {Array<CommentDTO>}
     * @memberof RantDTO
     */
    comments: Array<CommentDTO>;
    /**
     * 
     * @type {string}
     * @memberof RantDTO
     */
    owner: string;
    /**
     * 
     * @type {Date}
     * @memberof RantDTO
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof RantDTO
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof RantDTO
     */
    tags: Array<string>;
}

export function RantDTOFromJSON(json: any): RantDTO {
    return RantDTOFromJSONTyped(json, false);
}

export function RantDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RantDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'content': json['content'],
        'asset': AssetDTOFromJSON(json['asset']),
        'votes': !exists(json, 'votes') ? undefined : ((json['votes'] as Array<any>).map(VoteDTOFromJSON)),
        'userVoteState': !exists(json, 'userVoteState') ? undefined : json['userVoteState'],
        'score': json['score'],
        'comments': ((json['comments'] as Array<any>).map(CommentDTOFromJSON)),
        'owner': json['owner'],
        'updatedAt': (new Date(json['updatedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'tags': json['tags'],
    };
}

export function RantDTOToJSON(value?: RantDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'content': value.content,
        'asset': AssetDTOToJSON(value.asset),
        'votes': value.votes === undefined ? undefined : ((value.votes as Array<any>).map(VoteDTOToJSON)),
        'userVoteState': value.userVoteState,
        'score': value.score,
        'comments': ((value.comments as Array<any>).map(CommentDTOToJSON)),
        'owner': value.owner,
        'updatedAt': (value.updatedAt.toISOString()),
        'createdAt': (value.createdAt.toISOString()),
        'tags': value.tags,
    };
}


