/* tslint:disable */
/* eslint-disable */
/**
 * drant-community
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDTO
 */
export interface UserDTO {
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof UserDTO
     */
    score: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserDTO
     */
    social: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    about: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    skills: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    location: string;
    /**
     * 
     * @type {Date}
     * @memberof UserDTO
     */
    createdAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof UserDTO
     */
    supporter: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserDTO
     */
    moderator: boolean;
}

export function UserDTOFromJSON(json: any): UserDTO {
    return UserDTOFromJSONTyped(json, false);
}

export function UserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'name': json['name'],
        'score': json['score'],
        'social': json['social'],
        'about': json['about'],
        'skills': json['skills'],
        'location': json['location'],
        'createdAt': (new Date(json['createdAt'])),
        'supporter': json['supporter'],
        'moderator': json['moderator'],
    };
}

export function UserDTOToJSON(value?: UserDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'name': value.name,
        'score': value.score,
        'social': value.social,
        'about': value.about,
        'skills': value.skills,
        'location': value.location,
        'createdAt': (value.createdAt.toISOString()),
        'supporter': value.supporter,
        'moderator': value.moderator,
    };
}


